extend = [
  { path = "../cargo-make/main.toml" },
  { path = "../cargo-make/webdriver.toml" },
  { path = "../cargo-make/wasm-test.toml" },
  { path = "../cargo-make/trunk_server.toml" },
]

[tasks.test]
env = { RUN_CARGO_TEST = true }
condition = { env_true = ["RUN_CARGO_TEST"] }
